# Generated by Django 3.2.16 on 2023-03-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_auto_20230319_1102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default=None, null=True, upload_to="post/images/"),
        ),
    ]
